services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
  db:
    image: postgres:15
    container_name: fooddb_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: fooddb_meilisearch
    restart: always

    ports:
      - "7700:7700"

    env_file:
      - .env

    environment:
      MEILI_ENV: development

    volumes:
      - meili_data:/meili_data

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  migrate:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: ["alembic", "upgrade", "head"]

  meilisearch_setup:
    build: .
    depends_on:
      meilisearch:
        condition: service_healthy
    env_file:
      - .env

    command: ["python", "-m", "scripts.setup_meilisearch"]

  import:
    build: .
    depends_on:
      db:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
    env_file:
      - .env
    command: ["python", "-m", "scripts.import_openfoodfacts"]
    environment:
      - OPENFOODFACTS_FILE=/data/openfoodfacts.json
    volumes:
      - /data/openfoodfacts.json:/data/openfoodfacts.json


volumes:
  postgres_data:
  meili_data:
