"""Changed product table                                                                                                                                                                                        [0/0]

Revision ID: d0775425bc11
Revises: 840ebd6a3ba3
Create Date: 2026-05-07 17:05:08.032887

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d0775425bc11"
down_revision: Union[str, Sequence[str], None] = "840ebd6a3ba3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("completeness", sa.Float(), nullable=False))
    op.add_column("products", sa.Column("brand", sa.String(), nullable=True))
    op.drop_column("products", "nutritionFilledScore")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "nutritionFilledScore",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("products", "brand")
    op.drop_column("products", "completeness")
    # ### end Alembic commands ###
